name: Bandit Security Scan

on:
  workflow_dispatch:  # allow manual trigger
  push:
    branches: [ main, feature/basic-app ]
  pull_request:
    branches: [ main ]

jobs:
  bandit-scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # or your specific Python version

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        run: bandit -r . -f txt -o bandit-report.txt

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: bandit-report.txt
